USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_BI_XS
  WITH WAREHOUSE_SIZE = 'XSMALL'
       AUTO_SUSPEND = 300
       AUTO_RESUME = TRUE
       INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE WH_BI_XS;

CREATE DATABASE IF NOT EXISTS BD_RECUPERO;
USE DATABASE BD_RECUPERO;

CREATE SCHEMA IF NOT EXISTS ANALITICA;
USE SCHEMA BD_RECUPERO.ANALITICA;

CREATE STAGE IF NOT EXISTS STG_RECUPERO
  FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = ',' SKIP_HEADER = 1);

LIST @STG_RECUPERO;
