CREATE OR REPLACE TABLE DIM_TIEMPO (
  ID_TIEMPO     INTEGER NOT NULL,
  FECHA         DATE NOT NULL,
  ANIO          INTEGER NOT NULL,
  MES           INTEGER NOT NULL,
  NOMBRE_MES    STRING NOT NULL,
  TRIMESTRE     INTEGER NOT NULL,
  ES_FIN_DE_MES BOOLEAN NOT NULL
);

CREATE OR REPLACE TABLE DIM_AGENCIA (
  ID_AGENCIA      STRING NOT NULL,
  NOMBRE_AGENCIA  STRING NOT NULL,
  REGION          STRING NOT NULL
);

CREATE OR REPLACE TABLE DIM_OPERACION (
  ID_OPERACION   INTEGER NOT NULL,
  ID_DEUDOR      STRING NOT NULL,
  DOCUMENTO      INTEGER NOT NULL,
  ID_AGENCIA     STRING NOT NULL,
  FECHA_MORA     DATE NOT NULL,
  SALDO_INICIAL  NUMBER(18,2) NOT NULL,
  SALDO_ACTUAL   NUMBER(18,2) NOT NULL,
  TRAMO_MORA     STRING NOT NULL,
  TIPO_CARTERA   STRING NOT NULL
);
